#!/usr/bin/env python3
"""Extract ShuffleSubchannelColorData's loop VERBATIM from 012-canvas-get-image-data.patch.

WHY EXTRACT RATHER THAN RE-TYPE
-------------------------------
PS-373's round-3 finding is an arithmetic claim about our C++ ("the ``< 2`` clamp
forces us to modify pixelscan's 70x5 reference probe"). A re-typed copy of that
arithmetic proves nothing about the shipped patch — it proves something about my
typing, which is the PS-185 defect class (a document claiming provenance it does
not have). So the harness compiles the patch's OWN added lines: every line below
comes from a ``+`` line in the patch file, with the ``+`` stripped and nothing else
changed. If anyone edits the patch, the harness recompiles against the edit.

WHAT IS **NOT** VERBATIM, stated plainly: the scaffolding around the loop — the
Skia accessor macros, the colour-type enum, the buffer allocation and the
``seed_str`` binding. Chromium's tree is not in this container, so those are a
SHIM (``skia_shim.h``). The shim is modelled on Skia's documented little-endian
byte order and is validated by a round-trip self-test before any measurement runs
(see ``probe_harness.cc``'s ``SelfTestShim``).

The extraction window is anchored on two markers that are themselves part of the
behaviour, so a patch edit that removes them fails loudly rather than silently
extracting the wrong region.
"""

from __future__ import annotations

import pathlib
import sys

PATCH = (
    pathlib.Path(__file__).resolve().parents[3]
    / "engine"
    / "patches"
    / "fingerprint"
    / "012-canvas-get-image-data.patch"
)

# The first added line of the region we compile, and the identifier that must be
# the last thing it contains. Both are load-bearing behaviour, not formatting.
START_MARKER = "auto max_pixels = (w * h) / 128;"
END_ANCHOR = "default:"


def extract(patch_text: str) -> str:
    lines = patch_text.splitlines()

    start = None
    for i, line in enumerate(lines):
        if line.startswith("+") and START_MARKER in line:
            start = i
            break
    if start is None:
        raise SystemExit(
            f"FAIL: start marker {START_MARKER!r} not found on any added line of "
            f"{PATCH.name}. The patch changed shape; fix this extractor rather "
            f"than the harness."
        )

    # Walk forward collecting added lines. Context lines (' ') inside the region
    # would mean the loop is not wholly ours; there are none today, and if one
    # appears we want to know rather than silently drop it.
    body: list[str] = []
    saw_end_anchor = False
    i = start
    while i < len(lines):
        line = lines[i]
        if line.startswith("+"):
            content = line[1:]
            body.append(content)
            if END_ANCHOR in content:
                saw_end_anchor = True
        elif line.startswith("-"):
            pass  # deleted upstream lines are not our behaviour
        elif line.startswith("@@") or line.startswith("diff "):
            break
        elif saw_end_anchor and line.strip() in ("}", "}}"):
            # trailing context that closes the function
            break
        i += 1

    if not saw_end_anchor:
        raise SystemExit(
            f"FAIL: end anchor {END_ANCHOR!r} never seen while extracting from "
            f"{PATCH.name}."
        )

    # The added region ends with the switch's closing braces and the loop's; the
    # patch's trailing context supplies the function's own closing brace, which we
    # do not want. Balance the braces we collected.
    text = "\n".join(body)
    depth = 0
    cut = len(text)
    for idx, ch in enumerate(text):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                cut = idx
                break
    return text[:cut].rstrip()


def main() -> int:
    body = extract(PATCH.read_text(encoding="utf-8"))
    out = pathlib.Path(__file__).with_name("extracted_shuffle_body.inc")
    header = (
        "// GENERATED by extract_shuffle.py — DO NOT EDIT.\n"
        f"// Verbatim added lines of {PATCH.name}, '+' stripped.\n"
        "// Regenerate with:  python3 extract_shuffle.py\n"
    )
    out.write_text(header + body + "\n", encoding="utf-8")
    print(f"extracted {len(body.splitlines())} lines -> {out.name}")
    for probe in ("max_pixels < 2", "max_pixels = 2", "y < h - 1", "x < w - 1"):
        print(f"  contains {probe!r}: {probe in body}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
