COLORS = {
    "bg": "#000000",
    "sidebar": "#000000",
    "card_bg": "#000000",
    "card_hover": "#0A0A0A",
    "card_border": "#1AFFFFFF",
    "accent": "#A8FF3F",
    "accent_hover": "#7BBF2F",
    "accent_dim": "#66A8FF3F",
    "text_main": "#FFFFFF",
    "text_sub": "#BCBCBC",
    "text_dim": "#AAAAAA",
    "success": "#A8FF3F",
    "error": "#FF5252",
    "delete_hover": "#FF5252",
    "warning": "#E6B43C",
    "input_bg": "#0A0A0A",
    "border": "#1AFFFFFF",
    # A solid (not translucent) edge for row-action buttons — the translucent
    # card_border reads as a muddy grey-green ("болотный") on the row buttons.
    "btn_edge": "#2A2A2A",
    "edit": "#E6B43C",
    "rotate": "#5BC8FF",
    "scrollbar_bg": "#000000",
    "scrollbar_grab": "#2EFFFFFF",
    "log_bg": "#000000",
}
