"""Legal BCP 47 language subtags, VENDORED — the oracle the operator's declared
exit language is validated against.

GENERATED by ``scripts/ps332_vendor_language_subtags.py`` from the IANA
Language Subtag Registry. Do not hand-edit; re-run the script.

WHY THIS IS VENDORED RATHER THAN COMPUTED (PS-332, measured, not assumed):

    Python stdlib: no list of language subtags exists at all
    /usr/share/i18n/locales   (glibc only)      -> ABSENT on this container
    /usr/share/iso-codes/json (iso-codes pkg)   -> ABSENT on this container
    import babel / import pycountry             -> ModuleNotFoundError
    `locale -a`                                 -> absent on Windows entirely

There is therefore no OS-provided oracle that answers the same way on the three
platforms we ship — the situation PS-274 measured for timezones, one step
worse, because for languages the stdlib offers nothing to degrade from. The
operator's value feeds an engine as fact, so "accepted on my machine, refused
on yours" is not an acceptable property for it. Shipping the subtags as SOURCE
makes the accepted set identical on Windows, macOS and Linux by construction,
adds no dependency, and reads no OS locale database at runtime — which is also
what keeps every predicate in this module PURE (no IO), so the render layer can
call it.

This does NOT reintroduce a host-derived locale anywhere, and that prohibition
is stricter here than its timezone counterpart. ``#218`` forces ``en-US`` on
the direct path precisely so the host locale never leaks inside the tunnel;
this module answers only "is this string a real language subtag", never "what
language is this host in", and nothing on the launch path may ever ask the
second question.
"""

from __future__ import annotations

#: The IANA registry snapshot the list below was taken from (its own File-Date).
REGISTRY_FILE_DATE = "2026-08-08"

#: sha256 of the newline-separated subtag text below, so a refresh can be shown
#: to be a faithful copy of what the script produced rather than a hand edit.
LANGUAGE_SUBTAGS_SHA256 = "27b03451de5eb8b570917d385cdfc6b70ea0e32cf316a74e235ab4de24b0e0ef"

#: 184 newline-separated ISO 639-1 subtags, registry order.
_SUBTAGS_TEXT = """\
aa
ab
ae
af
ak
am
an
ar
as
av
ay
az
ba
be
bg
bi
bm
bn
bo
br
bs
ca
ce
ch
co
cr
cs
cu
cv
cy
da
de
dv
dz
ee
el
en
eo
es
et
eu
fa
ff
fi
fj
fo
fr
fy
ga
gd
gl
gn
gu
gv
ha
he
hi
ho
hr
ht
hu
hy
hz
ia
id
ie
ig
ii
ik
io
is
it
iu
ja
jv
ka
kg
ki
kj
kk
kl
km
kn
ko
kr
ks
ku
kv
kw
ky
la
lb
lg
li
ln
lo
lt
lu
lv
mg
mh
mi
mk
ml
mn
mr
ms
mt
my
na
nb
nd
ne
ng
nl
nn
no
nr
nv
ny
oc
oj
om
or
os
pa
pi
pl
ps
pt
qu
rm
rn
ro
ru
rw
sa
sc
sd
se
sg
sh
si
sk
sl
sm
sn
so
sq
sr
ss
st
su
sv
sw
ta
te
tg
th
ti
tk
tl
tn
to
tr
ts
tt
tw
ty
ug
uk
ur
uz
ve
vi
vo
wa
wo
xh
yi
yo
za
zh
zu
"""

#: The language subtags an operator may DECLARE for a proxy exit.
#:
#: TWO-LETTER (ISO 639-1) ONLY, and the narrowing is the shipped rule rather
#: than a new one: every value in ``_COUNTRY_LOCALE`` (``launch_policy.py``,
#: 241 rows) uses a two-letter language subtag, and a declared language is
#: consumed by the same engine argument as a table-derived one. Deprecated
#: registry entries (``in``, ``iw``, ``ji``, ``jw``, ``mo``, ``sh``) are
#: excluded: a modern engine reports their replacements back, so accepting one
#: would let the declared value and the observed value disagree.
DECLARABLE_LANGUAGE_SUBTAGS: frozenset[str] = frozenset(_SUBTAGS_TEXT.split())


def is_declarable_language(subtag: str) -> bool:
    """Whether ``subtag`` is a language an operator may declare for an exit.

    Pure and total: a membership test against the vendored set above, and NOT
    a pattern test — which is what makes it safe. ``[a-z]{2}`` would accept
    ``xx``, ``qq`` and ``zz``, none of which is a language, and each of which
    would then be composed into a locale string and handed to a browser engine
    as fact. A plausible-looking non-language is simply absent from the set, so
    it needs no rule of its own. Case is normalised because BCP 47 subtags are
    case-insensitive and conventionally lowercase; nothing else is.
    """
    return (subtag or "").strip().lower() in DECLARABLE_LANGUAGE_SUBTAGS
