"""Regenerate ``src/services/proxy/tz_names.py`` from the ``tzdata`` wheel.

PS-274 needs a set of legal IANA zone names that is **byte-identical on
Windows, macOS and Linux**, because the operator's declared zone is validated
against it before it is stored and then shipped to an engine as fact. Measured
on this project (the numbers are quoted in the ticket and re-measured here):

    zoneinfo, TZPATH=[]  (a bare Windows: no OS db, no tzdata)  ->   0 zones
    zoneinfo, TZPATH=[]  + the `tzdata` wheel present           -> 598 zones
    this Linux container (OS tz database)                       -> 486 zones

So ``zoneinfo.available_timezones()`` cannot be the oracle: it rejects every
input on a bare Windows and accepts a DIFFERENT set per OS. The name list is
therefore VENDORED IN-TREE — the wheel's own ``tzdata/zones`` resource, 598
newline-separated names, ~9 KB — and shipped as source. No dependency is added
and nothing reads the OS database at runtime.

Run it when the vendored list should be refreshed:

    python3 -m pip download tzdata -d /tmp/tzd --no-deps
    python3 -m zipfile -e /tmp/tzd/tzdata-*.whl /tmp/tzx
    python3 scripts/ps274_vendor_zone_names.py /tmp/tzx/tzdata/zones <version>

It is a SCRIPT, not a test and not a build step: the generated module is
committed, so a build never needs the wheel and a checkout is self-contained.
"""

from __future__ import annotations

import hashlib
import os
import pathlib
import sys

HEADER = '''"""Legal IANA timezone names, VENDORED — the oracle the operator's declared
exit zone is validated against.

GENERATED by ``scripts/ps274_vendor_zone_names.py`` from the ``tzdata`` wheel's
own ``tzdata/zones`` resource. Do not hand-edit; re-run the script.

WHY THIS IS VENDORED RATHER THAN COMPUTED (PS-274, measured, not assumed):

    zoneinfo, TZPATH=[]  (a bare Windows: no OS db, no tzdata)  ->   0 zones
    zoneinfo, TZPATH=[]  + the `tzdata` wheel present           -> 598 zones
    a typical Linux container (OS tz database)                  -> 486 zones

``zoneinfo.available_timezones()`` is therefore NOT a usable validator here: it
rejects every input on a bare Windows and yields a DIFFERENT accepted set on
each of the three platforms we ship. The operator's value feeds an engine as
fact, so "accepted on my machine, refused on yours" is not an acceptable
property for it. Shipping the names as SOURCE makes the accepted set identical
on Windows, macOS and Linux by construction, adds no dependency, and reads no
OS database at runtime — which is also what keeps every predicate in this
module PURE (no IO), so the render layer can call it.

This does NOT reintroduce a host-derived zone anywhere: the module answers only
"is this string a real zone name", never "what zone is this host in".
"""

from __future__ import annotations

#: The tzdata release the list below was taken from.
TZDATA_VERSION = "{version}"

#: sha256 of the verbatim ``tzdata/zones`` resource this was generated from, so
#: a refresh can be shown to be a faithful copy rather than a hand edit.
TZDATA_ZONES_SHA256 = "{sha}"

#: The wheel resource VERBATIM: {count} newline-separated names, in its own order.
_ZONES_TEXT = """\\
{body}"""

#: Every name tzdata ships, legacy aliases and bare abbreviations included.
ALL_ZONE_NAMES: frozenset[str] = frozenset(_ZONES_TEXT.split())

#: The names an operator may DECLARE — the ``Region/City`` form only.
#:
#: Narrower than ALL_ZONE_NAMES on purpose, and the narrowing is the shipped
#: rule rather than a new one: ``proxy_checker._validate_geo`` already keeps a
#: MEASURED zone only when it contains "/", precisely so a bare abbreviation
#: ("EET") never reaches the launch path. A declared zone is consumed by the
#: same code as a measured one, so it is held to the same shape. The legacy
#: aliases this drops ("Poland", "Turkey", "Zulu", "GMT+0", ...) each have a
#: Region/City spelling that is accepted.
DECLARABLE_ZONE_NAMES: frozenset[str] = frozenset(
    name for name in ALL_ZONE_NAMES if "/" in name
)


def is_declarable_zone(name: str) -> bool:
    """Whether ``name`` is a zone an operator may declare for a proxy exit.

    Pure and total: a membership test against the vendored set above. It is a
    SET test rather than a pattern test, which is what makes it safe — a
    plausible-looking string ("Not/AZone"), a bare abbreviation ("EET") and a
    traversal attempt ("../../etc/passwd", "Europe/../../../etc/passwd") are
    all simply absent from the set, so none of them needs its own rule. The
    value is stored and later handed to a browser engine as a real zone; a
    shape check would let every one of those through.
    """
    return (name or "").strip() in DECLARABLE_ZONE_NAMES
'''


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src = pathlib.Path(sys.argv[1])
    version = sys.argv[2]
    raw = src.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    text = raw.decode("ascii")
    names = [line for line in text.splitlines() if line.strip()]
    for name in names:
        # The list is embedded in a python string literal; anything needing an
        # escape would make "verbatim" a lie. tzdata has never shipped one.
        if '"' in name or "\\" in name or name != name.strip():
            raise SystemExit(f"unexpected zone name {name!r}")
    out = pathlib.Path(
        os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "src",
            "services",
            "proxy",
            "tz_names.py",
        )
    )
    out.write_text(
        HEADER.format(
            version=version,
            sha=sha,
            count=len(names),
            body="\n".join(names) + "\n",
        ),
        encoding="utf-8",
    )
    print(f"wrote {out} — {len(names)} names, sha256 {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
