"""Regenerate ``src/services/proxy/language_names.py`` from the IANA registry.

PS-332 needs a set of legal language subtags that is **byte-identical on
Windows, macOS and Linux**, for exactly the reason PS-274 vendored the IANA
zone names: the operator's declared value is validated before it is stored and
is then handed to a browser engine as fact, so "accepted on my machine, refused
on yours" is not an acceptable property for it.

There is no ``available_locales()`` to reject in the way ``zoneinfo`` was
rejected — the situation is worse. Python's stdlib exposes NO list of language
subtags at all; the nearest OS-provided oracles are ``locale -a`` (absent on
Windows entirely), ``/usr/share/i18n/locales`` (glibc only — absent on macOS
and Windows, and absent in a musl container), and ``babel``/``pycountry``
(new runtime dependencies, each carrying its own CLDR snapshot). Measured on
this project's own container while writing this script:

    /usr/share/i18n/locales                     -> ABSENT
    /usr/share/iso-codes/json                   -> ABSENT
    import pycountry / import babel             -> ModuleNotFoundError

So the accepted set is VENDORED IN-TREE from the IANA Language Subtag Registry
(the BCP 47 oracle, RFC 5646's own source of truth) and shipped as source. No
dependency is added and nothing reads an OS locale database at runtime, which
is also what keeps every predicate in the module PURE (no IO) so the render
layer can call it.

Run it when the vendored list should be refreshed:

    curl -o /tmp/lsr.txt \\
      https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
    python3 scripts/ps332_vendor_language_subtags.py /tmp/lsr.txt

It is a SCRIPT, not a test and not a build step: the generated module is
committed, so a build never needs the registry and a checkout is
self-contained. The script prints the File-Date it read; that date is what
lands in ``REGISTRY_FILE_DATE``.

WHAT IS KEPT, AND WHY IT IS THE TWO-LETTER SUBTAGS ONLY
------------------------------------------------------
The registry carries ``Type: language`` records with two-letter (ISO 639-1) and
three-letter (ISO 639-3) subtags. Only the TWO-LETTER ones are vendored, which
is not an arbitrary narrowing: every value in ``_COUNTRY_LOCALE``
(``launch_policy.py``, 241 rows) uses a two-letter language subtag, so the
shipped table is the shape the declaration must be interchangeable with. A
declared locale is consumed by the SAME engine argument as a table-derived one,
so it is held to the same shape — the same reasoning that narrows
``DECLARABLE_ZONE_NAMES`` to the ``Region/City`` form.

Records marked ``Deprecated`` are dropped: the registry keeps ``in``, ``iw``,
``ji``, ``jw``, ``mo`` and ``sh`` forever with a ``Preferred-Value`` pointing
at their replacement, and accepting a deprecated tag would let an operator
declare a language a modern engine reports back under a different name — a
disagreement between what was declared and what the page sees.
"""

from __future__ import annotations

import hashlib
import pathlib
import sys

HEADER = '''"""Legal BCP 47 language subtags, VENDORED — the oracle the operator's declared
exit language is validated against.

GENERATED by ``scripts/ps332_vendor_language_subtags.py`` from the IANA
Language Subtag Registry. Do not hand-edit; re-run the script.

WHY THIS IS VENDORED RATHER THAN COMPUTED (PS-332, measured, not assumed):

    Python stdlib: no list of language subtags exists at all
    /usr/share/i18n/locales   (glibc only)      -> ABSENT on this container
    /usr/share/iso-codes/json (iso-codes pkg)   -> ABSENT on this container
    import babel / import pycountry             -> ModuleNotFoundError
    `locale -a`                                 -> absent on Windows entirely

There is therefore no OS-provided oracle that answers the same way on the three
platforms we ship — the situation PS-274 measured for timezones, one step
worse, because for languages the stdlib offers nothing to degrade from. The
operator's value feeds an engine as fact, so "accepted on my machine, refused
on yours" is not an acceptable property for it. Shipping the subtags as SOURCE
makes the accepted set identical on Windows, macOS and Linux by construction,
adds no dependency, and reads no OS locale database at runtime — which is also
what keeps every predicate in this module PURE (no IO), so the render layer can
call it.

This does NOT reintroduce a host-derived locale anywhere, and that prohibition
is stricter here than its timezone counterpart. ``#218`` forces ``en-US`` on
the direct path precisely so the host locale never leaks inside the tunnel;
this module answers only "is this string a real language subtag", never "what
language is this host in", and nothing on the launch path may ever ask the
second question.
"""

from __future__ import annotations

#: The IANA registry snapshot the list below was taken from (its own File-Date).
REGISTRY_FILE_DATE = "{file_date}"

#: sha256 of the newline-separated subtag text below, so a refresh can be shown
#: to be a faithful copy of what the script produced rather than a hand edit.
LANGUAGE_SUBTAGS_SHA256 = "{sha}"

#: {count} newline-separated ISO 639-1 subtags, registry order.
_SUBTAGS_TEXT = """\\
{body}"""

#: The language subtags an operator may DECLARE for a proxy exit.
#:
#: TWO-LETTER (ISO 639-1) ONLY, and the narrowing is the shipped rule rather
#: than a new one: every value in ``_COUNTRY_LOCALE`` (``launch_policy.py``,
#: 241 rows) uses a two-letter language subtag, and a declared language is
#: consumed by the same engine argument as a table-derived one. Deprecated
#: registry entries (``in``, ``iw``, ``ji``, ``jw``, ``mo``, ``sh``) are
#: excluded: a modern engine reports their replacements back, so accepting one
#: would let the declared value and the observed value disagree.
DECLARABLE_LANGUAGE_SUBTAGS: frozenset[str] = frozenset(_SUBTAGS_TEXT.split())


def is_declarable_language(subtag: str) -> bool:
    """Whether ``subtag`` is a language an operator may declare for an exit.

    Pure and total: a membership test against the vendored set above, and NOT
    a pattern test — which is what makes it safe. ``[a-z]{{2}}`` would accept
    ``xx``, ``qq`` and ``zz``, none of which is a language, and each of which
    would then be composed into a locale string and handed to a browser engine
    as fact. A plausible-looking non-language is simply absent from the set, so
    it needs no rule of its own. Case is normalised because BCP 47 subtags are
    case-insensitive and conventionally lowercase; nothing else is.
    """
    return (subtag or "").strip().lower() in DECLARABLE_LANGUAGE_SUBTAGS
'''


def _records(text: str) -> list[dict[str, list[str]]]:
    out = []
    for chunk in text.split("\n%%\n")[1:]:
        fields: dict[str, list[str]] = {}
        lines: list[str] = []
        for line in chunk.split("\n"):
            # The registry folds long values onto continuation lines indented
            # by two spaces; unfold before parsing so a folded Description
            # cannot be mistaken for a field of its own.
            if line.startswith("  ") and lines:
                lines[-1] += " " + line.strip()
            else:
                lines.append(line)
        for line in lines:
            if ": " in line:
                key, value = line.split(": ", 1)
                fields.setdefault(key, []).append(value)
        out.append(fields)
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    raw = pathlib.Path(argv[1]).read_text(encoding="utf-8")
    file_date = ""
    for line in raw.split("\n%%\n")[0].splitlines():
        if line.startswith("File-Date:"):
            file_date = line.split(":", 1)[1].strip()
    subtags = []
    for record in _records(raw):
        if record.get("Type", [None])[0] != "language":
            continue
        subtag = record["Subtag"][0]
        if len(subtag) != 2 or "Deprecated" in record:
            continue
        subtags.append(subtag)
    body = "\n".join(subtags) + "\n"
    sha = hashlib.sha256(body.encode()).hexdigest()
    out = pathlib.Path(__file__).resolve().parents[1] / (
        "src/services/proxy/language_names.py"
    )
    out.write_text(
        HEADER.format(
            file_date=file_date, sha=sha, count=len(subtags), body=body
        ),
        encoding="utf-8",
    )
    print(f"wrote {out} — {len(subtags)} subtags, File-Date {file_date}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
