#!/usr/bin/env python3
"""Re-sign the macOS slices WE build with the hardened runtime and without
`com.apple.security.get-task-allow`, so the bundle stops carrying two
purchase-independent notarization-rejection conditions.

PS-386. Read `readings/ps346-2026-09-07/REPORT.md` first — this script exists to
move two specific figures that report measured on the published 3.1.1 bytes:

    CodeDirectory flags = 0x2   adhoc: True   runtime (0x10000): False
    hardened-runtime slices: 1/225      <- and that ONE is vendored Node.js
    <key>com.apple.security.get-task-allow</key><true/>   on 3/3 our slices

WHY A RE-SIGN AND NOT A BUILD FLAG
----------------------------------
This was not a preference. `ENABLE_HARDENED_RUNTIME` and `OTHER_CODE_SIGN_FLAGS`
occur NOWHERE in flet's build template (v0.85.3) and NOWHERE in flet-cli 0.85.3
itself — measured by grep over both, zero hits. flet exposes seams for
entitlements (`tool.flet.macos.entitlement`), for Flutter build args
(`tool.flet.flutter.build_args`), and for nothing else; there is no
xcode-build-setting passthrough of any kind. So no edit to `pyproject.toml`
can turn the hardened runtime on, and the generated Xcode project lives under
`build/`, which is gitignored and regenerated by the next `flet build`.

⛔ THAT IS THE TRAP THIS SCRIPT EXISTS TO AVOID. Editing the generated
`project.pbxproj` or the generated `Release.entitlements` "works" exactly once
and is silently reverted by the next build, which would leave a green commit
and an unchanged artifact. Re-signing the produced `.app` is the only seam that
survives regeneration.

⭐ SIGNING IS BUNDLE-AWARE, AND THAT IS THE LOAD-BEARING PART
-------------------------------------------------------------
`codesign` seals a bundle over its contents: the seal is a manifest of digests
in `_CodeSignature/CodeResources`. PS-346 measured **20 such seals** inside this
one `.app` — it is not one bundle, it is a tree of them (the
`serious_python_darwin.framework`, the `python.bundle` inside it, the Flutter
frameworks). So re-signing a nested bundle's INNER BINARY as if it were a loose
file rewrites bytes that its own enclosing seal already committed to, and every
seal above it goes stale at once. `codesign --verify --deep --strict` then
fails, and the artifact is worse than the one we started with.

Two rules follow, and both are tested:

  1. A nested bundle is signed **at its bundle root**, never at its inner
     binary — that is what makes `codesign` rewrite the seal instead of
     invalidating it.
  2. Everything is signed **deepest first**, so a container is only ever sealed
     over contents that have already reached their final bytes.

WHAT IT SIGNS, AND WHAT IT DELIBERATELY DOES NOT
-------------------------------------------------
⭐ ONLY THE SLICES WE PRODUCE. The honest target named by PS-386 is "every slice
we build" and explicitly NOT a bundle-wide `225/225`, which would misreport
vendored third-party code we did not sign and did not produce. PS-346 measured
`SIGNED_CMS=1` in this bundle: the Node.js Foundation's `node`, vendored under
playwright's driver, which arrived already signed. Re-signing it would DESTROY a
genuine signature and replace it with our ad-hoc one — strictly worse than
leaving it alone.

⚠️ ONE identity, not two. Microsoft's signed `d3dcompiler_47.dll` / `dxil.dll`
DO exist in PS-346's reading, but they are PE files in the WINDOWS engine zip
and are not in this bundle at all. Reading a Windows-asset finding as a
macOS-bundle fact is exactly the cross-asset conflation PS-346's report was
careful to avoid, and it must not be the justification for a guard on this path.

So this walks the bundle and skips anything already carrying a CMS signature
(a real identity), re-signing only ad-hoc/unsigned Mach-O code.

⚠️ ENTITLEMENTS GO ON BUNDLES, NOT ON EVERY DYLIB, and that asymmetry is
deliberate rather than an oversight. An entitlement blob is a statement about a
PROCESS, so it belongs on the executable the kernel launches; stamping one onto
each of ~200 loose dylibs would invent ~200 entitlement blobs where the shipped
artifact has three, and every one of them would be a new place for
`get-task-allow` to be re-injected. Loose code gets `--options runtime` and
nothing else. PS-346's reading corroborates the shape: entitlements were found
on 3 slices out of 225, not on all of them.

⛔ NO CREDENTIAL, EVER. This signs ad-hoc (`--sign -`), exactly as the build
already does. It CANNOT and MUST NOT produce a signed or notarized artifact:
that needs an Apple Developer Program membership under a chosen legal identity,
which is a purchase decision reserved to the owner. What this removes is the two
blockers that would make such a submission fail EVEN IF the identity existed.
An ad-hoc signature with the hardened runtime is still not notarizable — it is
notarization-READY, which is the whole and only claim here.

⚠️ THIS SCRIPT ASSERTS A POSTURE; IT DOES NOT MEASURE ONE. Whether `codesign`
honoured what was asked — in particular whether it re-injected
`get-task-allow` anyway, which is exactly what it does when left to itself — is
a question about the produced BYTES, and it is answered by
`scripts/ps386_verify_posture.py`, which reads them with PS-346's own audited
readers. Do not read a zero exit here as a measured result.

USAGE
-----
    python3 scripts/ps386_macos_harden.py --app build/macos/Build/Products/Release/persona.app
    python3 scripts/ps386_macos_harden.py --app <path> --dry-run

Exit codes:
    0  every targeted item re-signed and the bundle verifies
    1  an item failed to re-sign, or the bundle failed verification
    2  the environment cannot do this (not macOS / no codesign / bad --app)

⚠️ EXIT 2 IS NOT A PASS. It means the question was not asked.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

# The entitlement set we assert on our own bundles. This MUST be kept in step
# with `[tool.flet.macos.entitlement]` in pyproject.toml — the two exist for
# different reasons (that one states intent into the generated plist, this one
# is what codesign actually applies), and `--check-pyproject` asserts they agree
# rather than leaving it to a reader to notice.
#
# ⛔ DO NOT SWEEP THESE TO MAKE A CHECKER GREEN. `cs.allow-jit` is very probably
# REQUIRED by the bundled CPython; removing it trades a notarization
# prerequisite for an app that does not launch. `get-task-allow` is the only key
# being deliberately turned off, and it is the one the notary rejects.
ENTITLEMENTS: dict[str, bool] = {
    "com.apple.security.app-sandbox": False,
    "com.apple.security.cs.allow-jit": True,
    "com.apple.security.network.client": True,
    "com.apple.security.network.server": True,
    "com.apple.security.files.user-selected.read-write": True,
    "com.apple.security.get-task-allow": False,
}

MACHO_MAGICS = {
    b"\xcf\xfa\xed\xfe",  # MH_MAGIC_64  (little-endian)
    b"\xce\xfa\xed\xfe",  # MH_MAGIC     (little-endian)
    b"\xca\xfe\xba\xbe",  # FAT_MAGIC
    b"\xbe\xba\xfe\xca",  # FAT_CIGAM
}

# Directory suffixes that mean "this is a bundle, sign it at the root".
BUNDLE_SUFFIXES = (".framework", ".bundle", ".app", ".xpc", ".appex")


def is_macho(path: Path) -> bool:
    """Does this file begin with a Mach-O or fat-binary magic?

    Read by MAGIC rather than by extension: the slices that matter here are
    `.dylib`, `.so`, bare executables inside `Contents/MacOS`, and frameworks
    with no extension at all. An extension allow-list would miss most of them.
    """
    try:
        with open(path, "rb") as fh:
            return fh.read(4) in MACHO_MAGICS
    except OSError:
        return False


def classify(path: Path) -> tuple[str, str]:
    """OURS / THIRD_PARTY / UNREADABLE — three values, because three things happen.

    ⭐ THIS USED TO BE A BOOLEAN AND THAT WAS THE DEFECT. Collapsing "could not
    tell" into "third-party" is the same class of error PS-346's instrument was
    hardened against across five rework rounds: a three-valued fact rendered as
    two, so the run reports a clean count over slices nobody could read.

    `codesign -dvvv` prints an `Authority=` line only for a genuine signature;
    an ad-hoc one has no authority chain at all. So:

      * exit 0 with `Authority=`     -> THIRD_PARTY (a real certificate signed it)
      * exit 0 without `Authority=`  -> OURS        (ad-hoc or unsigned)
      * anything else                -> UNREADABLE  (we do not know)

    ⚠️ THE NON-ZERO EXIT ARM IS THE ONE THAT MATTERED. `subprocess.run` without
    `check=True` does NOT raise on a non-zero exit, so a `codesign` that errored
    per-slice previously fell through the `Authority=` test to False and was
    RE-SIGNED as ours. That is the most likely per-slice failure mode, and it
    was the one the old fail-safe did not actually cover.

    UNREADABLE is treated as third-party for the SIGNING decision — skipping a
    slice we could have hardened is a shortfall the verifier reports, while
    destroying a real signature is not recoverable — but it is COUNTED AND
    PRINTED separately, so a blind skip can never be mistaken for a legitimate
    third-party one.
    """
    try:
        out = subprocess.run(
            ["codesign", "-dvvv", str(path)],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return "UNREADABLE", f"{type(exc).__name__}"
    blob = (out.stderr or "") + (out.stdout or "")
    if out.returncode != 0:
        first = next((ln for ln in blob.splitlines() if ln.strip()), "")
        return "UNREADABLE", f"codesign exit {out.returncode}: {first[:120]}"
    if "Authority=" in blob:
        authority = next(
            (ln.strip() for ln in blob.splitlines() if ln.strip().startswith("Authority=")),
            "Authority=?",
        )
        return "THIRD_PARTY", authority[:160]
    return "OURS", ""


def bundle_main_executable(bundle: Path) -> Path | None:
    """The binary `codesign` will sign when handed this bundle root.

    Needed so the same binary is not ALSO signed as a loose file: signing it
    directly and then signing its bundle is not merely wasteful, it means the
    loose pass writes entitlements onto a slice the bundle pass then rewrites,
    and the artifact's entitlement count stops matching what this script says
    it applied.
    """
    for info in (
        bundle / "Contents" / "Info.plist",
        bundle / "Resources" / "Info.plist",
        bundle / "Versions" / "Current" / "Resources" / "Info.plist",
        bundle / "Versions" / "A" / "Resources" / "Info.plist",
    ):
        if not info.is_file():
            continue
        try:
            with open(info, "rb") as fh:
                plist = plistlib.load(fh)
        except Exception:
            continue
        name = plist.get("CFBundleExecutable")
        if not name:
            continue
        for cand in (
            bundle / "Contents" / "MacOS" / name,
            bundle / "Versions" / "A" / name,
            bundle / "Versions" / "Current" / name,
            bundle / name,
        ):
            if cand.is_file() and not cand.is_symlink():
                return cand
    # A `.framework` may carry no Info.plist we can read; its binary is
    # conventionally Versions/A/<framework name>.
    if bundle.suffix == ".framework":
        cand = bundle / "Versions" / "A" / bundle.stem
        if cand.is_file() and not cand.is_symlink():
            return cand
    return None


def find_nested_bundles(app: Path) -> list[Path]:
    """Every bundle inside the app — the things that must be signed AT THE ROOT.

    PS-346 counted 20 `_CodeSignature/CodeResources` seals in this one `.app`,
    which is what a tree of nested bundles looks like from the outside. Each of
    those seals is a manifest of digests over that bundle's contents, so each
    one is a thing that goes stale if its contents are rewritten under it.
    """
    out = []
    for path in app.rglob("*"):
        if path.is_symlink() or not path.is_dir():
            continue
        if path.suffix in BUNDLE_SUFFIXES:
            out.append(path)
    return out


def plan(app: Path) -> tuple[list[Path], list[Path]]:
    """Return (items_to_sign_deepest_first, bundle_roots).

    An "item" is either a nested bundle root or a loose Mach-O file that is not
    some bundle's main executable. Ordering is by path depth, DESCENDING.

    ⚠️ DEEPEST FIRST IS LOAD-BEARING, not tidiness. codesign seals a bundle over
    its contents, so an outer bundle signed before its nested code has its seal
    invalidated the instant the inner code changes. Nested code must reach its
    final bytes before the thing that contains it is sealed.
    """
    bundles = find_nested_bundles(app)
    mains = {m for b in bundles if (m := bundle_main_executable(b)) is not None}
    app_main = bundle_main_executable(app)
    if app_main is not None:
        mains.add(app_main)

    loose = [
        p
        for p in app.rglob("*")
        if p.is_file() and not p.is_symlink() and p not in mains and is_macho(p)
    ]
    items = bundles + loose
    items.sort(key=lambda p: len(p.parts), reverse=True)
    return items, bundles


def check_pyproject(root: Path) -> int:
    """Assert pyproject's declared entitlements match what this script applies.

    The two live apart on purpose (see ENTITLEMENTS above), and a silent drift
    between them is exactly the defect that would let a future editor change one
    and ship the other.
    """
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - py<3.11
        print("SKIP: tomllib unavailable", file=sys.stderr)
        return 0

    pyproject = root / "pyproject.toml"
    with open(pyproject, "rb") as fh:
        data = tomllib.load(fh)
    declared = data.get("tool", {}).get("flet", {}).get("macos", {}).get("entitlement")
    if declared is None:
        print(f"FAIL: [tool.flet.macos.entitlement] missing from {pyproject}", file=sys.stderr)
        return 1
    if declared != ENTITLEMENTS:
        print("FAIL: pyproject entitlements disagree with this script.", file=sys.stderr)
        for key in sorted(set(declared) | set(ENTITLEMENTS)):
            lhs, rhs = declared.get(key, "<absent>"), ENTITLEMENTS.get(key, "<absent>")
            if lhs != rhs:
                print(f"  {key}: pyproject={lhs!r} script={rhs!r}", file=sys.stderr)
        return 1
    print(f"OK: pyproject and script agree on {len(ENTITLEMENTS)} entitlements.")
    return 0


def sign_cmd(target: Path, ents: Path | None) -> list[str]:
    """The exact `codesign` invocation, in one place so a test can read it.

    `--sign -` is ad-hoc and is the ONLY identity this script can use.
    `--options runtime` is the whole point. `--entitlements` is passed only for
    bundles (see the module docstring).
    """
    cmd = ["codesign", "--force", "--sign", "-", "--options", "runtime", "--timestamp=none"]
    if ents is not None:
        cmd += ["--entitlements", str(ents)]
    cmd.append(str(target))
    return cmd


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--app", help="path to the built .app bundle")
    ap.add_argument("--dry-run", action="store_true", help="list what would be signed, sign nothing")
    ap.add_argument(
        "--check-pyproject",
        action="store_true",
        help="assert pyproject's entitlements match this script's, then exit (runs anywhere)",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent

    if args.check_pyproject:
        return check_pyproject(root)

    if not args.app:
        print("FAIL: --app is required (or use --check-pyproject)", file=sys.stderr)
        return 2

    app = Path(args.app)
    if not app.is_dir() or app.suffix != ".app":
        print(f"CANNOT RUN: not an .app bundle: {app}", file=sys.stderr)
        return 2
    if sys.platform != "darwin":
        print(f"CANNOT RUN: this needs macOS, not {sys.platform}.", file=sys.stderr)
        print("⚠️  This is NOT a pass — the question was not asked.", file=sys.stderr)
        return 2
    if shutil.which("codesign") is None:
        print("CANNOT RUN: `codesign` not on PATH.", file=sys.stderr)
        return 2

    ents_path = Path(os.environ.get("TMPDIR", "/tmp")) / "ps386_entitlements.plist"
    with open(ents_path, "wb") as fh:
        plistlib.dump(ENTITLEMENTS, fh)
    print(f"entitlements written to {ents_path}")
    for key, value in ENTITLEMENTS.items():
        print(f"    {key} = {value}")

    items, bundles = plan(app)
    bundle_set = set(bundles)
    print(f"\n{len(items)} item(s) to consider in {app}")
    print(f"  {len(bundles)} nested bundle(s) — signed AT THE ROOT so their seals are rewritten")
    print(f"  {len(items) - len(bundles)} loose Mach-O file(s)")

    ours: list[Path] = []
    theirs: list[tuple[Path, str]] = []
    unreadable: list[tuple[Path, str]] = []
    for path in items:
        state, detail = classify(path)
        if state == "OURS":
            ours.append(path)
        elif state == "THIRD_PARTY":
            theirs.append((path, detail))
        else:
            unreadable.append((path, detail))

    print(f"\n  {len(ours)} OURS (ad-hoc/unsigned) -> WILL be re-signed")
    print(f"  {len(theirs)} THIRD_PARTY (a real certificate) -> LEFT ALONE")
    for path, detail in theirs:
        print(f"      skip: {path.relative_to(app)}")
        print(f"            {detail}")
    print(f"  {len(unreadable)} UNREADABLE (we could not tell) -> LEFT ALONE")
    for path, detail in unreadable:
        print(f"      skip: {path.relative_to(app)}")
        print(f"            {detail}")
    if unreadable:
        # ⚠️ NOT FATAL, BUT NEVER INVISIBLE. These are slices we might have been
        # able to harden and did not. The verifier reads the produced bytes and
        # will report any of them that lack the runtime flag, so the shortfall
        # surfaces as a measured miss rather than as a silent one — but it must
        # be legible HERE too, or a count of "re-signed N" reads as complete.
        print(
            f"\n⚠️  {len(unreadable)} slice(s) could NOT be classified and were left\n"
            "    alone. They are NOT third-party — they are unknown. The final\n"
            "    count below therefore covers the slices this run CHOSE to target,\n"
            "    not every slice in the bundle. scripts/ps386_verify_posture.py\n"
            "    reads the produced bytes and will fail on any of these that\n"
            "    ships without the hardened runtime."
        )

    if args.dry_run:
        print("\n--dry-run: nothing was signed.")
        print("Sign order would be (deepest first, first 20):")
        for path in ours[:20]:
            kind = "bundle" if path in bundle_set else "file"
            print(f"    [{kind}] {path.relative_to(app)}")
        return 0

    failures: list[tuple[Path, str]] = []
    for path in ours:
        # Entitlements describe a PROCESS, so they go on bundles only. Loose
        # dylibs get the runtime option and no entitlement blob — see the
        # module docstring for why stamping ~200 of them would be a regression.
        ents = ents_path if path in bundle_set else None
        res = subprocess.run(sign_cmd(path, ents), capture_output=True, text=True)
        if res.returncode != 0:
            failures.append((path, (res.stderr or "").strip()))

    # The app itself LAST — it seals over everything signed above.
    res = subprocess.run(sign_cmd(app, ents_path), capture_output=True, text=True)
    if res.returncode != 0:
        failures.append((app, (res.stderr or "").strip()))

    print(f"\nre-signed {len(ours)} item(s) + the app bundle")

    if failures:
        print(f"\nFAILED on {len(failures)} item(s):", file=sys.stderr)
        for path, err in failures:
            print(f"  {path}: {err}", file=sys.stderr)
        return 1

    verify = subprocess.run(
        ["codesign", "--verify", "--deep", "--strict", "--verbose=2", str(app)],
        capture_output=True,
        text=True,
    )
    print("\n--- codesign --verify --deep --strict ---")
    print((verify.stderr or verify.stdout or "").strip())
    if verify.returncode != 0:
        print("FAIL: the bundle does not verify after re-signing.", file=sys.stderr)
        return 1

    print(f"\nOK: {len(ours)} targeted item(s) re-signed with --options runtime, and")
    print("    the bundle still verifies --deep --strict (its seals were rewritten,")
    print("    not invalidated).")
    if unreadable:
        print(
            f"⚠️  ...but {len(unreadable)} slice(s) were UNREADABLE and skipped. This run\n"
            "    is COMPLETE OVER WHAT IT COULD CLASSIFY, not over the bundle."
        )
    print(
        "\n⚠️  THIS IS NOT A NOTARIZED OR IDENTITY-SIGNED BUILD, and must not be\n"
        "    reported as one. The signature is still AD-HOC and carries no\n"
        "    certificate. What changed is that the two purchase-independent\n"
        "    rejection conditions are addressed: the hardened runtime is asked\n"
        "    for, and get-task-allow is declared false. Notarization still needs\n"
        "    the Apple Developer Program membership, which is the owner's\n"
        "    decision.\n"
        "\n⛔  A PASS HERE IS NOT A MEASUREMENT. This says codesign accepted what\n"
        "    it was asked; it does NOT say the produced bytes carry the posture.\n"
        "    Run scripts/ps386_verify_posture.py, which reads them with PS-346's\n"
        "    own readers.\n"
        "\n⛔  AND IT IS NOT OUTCOME 4. It says nothing about whether the app\n"
        "    still launches or still spawns an engine. Launch it."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
