#!/usr/bin/env python3
"""Re-sign the macOS slices WE build with the hardened runtime and without
`com.apple.security.get-task-allow`, so the bundle stops carrying two
purchase-independent notarization-rejection conditions.

PS-386. Read `readings/ps346-2026-09-07/REPORT.md` first — this script exists to
move two specific figures that report measured on the published 3.1.1 bytes:

    CodeDirectory flags = 0x2   adhoc: True   runtime (0x10000): False
    hardened-runtime slices: 1/225      <- and that ONE is vendored Node.js
    <key>com.apple.security.get-task-allow</key><true/>   on 3/3 our slices

WHY A RE-SIGN AND NOT A BUILD FLAG
----------------------------------
This was not a preference. `ENABLE_HARDENED_RUNTIME` and `OTHER_CODE_SIGN_FLAGS`
occur NOWHERE in flet's build template (v0.85.3) and NOWHERE in flet-cli 0.85.3
itself — measured by grep over both, zero hits. flet exposes seams for
entitlements (`tool.flet.macos.entitlement`), for Flutter build args
(`tool.flet.flutter.build_args`), and for nothing else; there is no
xcode-build-setting passthrough of any kind. So no edit to `pyproject.toml`
can turn the hardened runtime on, and the generated Xcode project lives under
`build/`, which is gitignored and regenerated by the next `flet build`.

⛔ THAT IS THE TRAP THIS SCRIPT EXISTS TO AVOID. Editing the generated
`project.pbxproj` or the generated `Release.entitlements` "works" exactly once
and is silently reverted by the next build, which would leave a green commit
and an unchanged artifact. Re-signing the produced `.app` is the only seam that
survives regeneration.

WHAT IT SIGNS, AND WHAT IT DELIBERATELY DOES NOT
-------------------------------------------------
⭐ ONLY THE SLICES WE PRODUCE. The honest target named by PS-386 is "every slice
we build" and explicitly NOT a bundle-wide `225/225`, which would misreport
vendored third-party code we did not sign and did not produce. Two vendored
binaries in this bundle carry REAL third-party identities — Node.js
Foundation's `node`, and Microsoft's redistributables in the engine — and
re-signing those would DESTROY a genuine signature and replace it with our
ad-hoc one. That is strictly worse than leaving them alone.

So this walks the bundle and skips anything already carrying a CMS signature
(a real identity), re-signing only ad-hoc/unsigned Mach-O slices.

⛔ NO CREDENTIAL, EVER. This signs ad-hoc (`--sign -`), exactly as the build
already does. It CANNOT and MUST NOT produce a signed or notarized artifact:
that needs an Apple Developer Program membership under a chosen legal identity,
which is a purchase decision reserved to the owner. What this removes is the two
blockers that would make such a submission fail EVEN IF the identity existed.
An ad-hoc signature with the hardened runtime is still not notarizable — it is
notarization-READY, which is the whole and only claim here.

USAGE
-----
    python3 scripts/ps386_macos_harden.py --app build/macos/Build/Products/Release/persona.app
    python3 scripts/ps386_macos_harden.py --app <path> --dry-run

Exit codes:
    0  every targeted slice re-signed and verified
    1  a slice failed to re-sign or failed verification
    2  the environment cannot do this (not macOS / no codesign / bad --app)

⚠️ EXIT 2 IS NOT A PASS. It means the question was not asked.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

# The entitlement set we assert on our own slices. This MUST be kept in step
# with `[tool.flet.macos.entitlement]` in pyproject.toml — the two exist for
# different reasons (that one states intent into the generated plist, this one
# is what codesign actually applies), and `--check-pyproject` asserts they agree
# rather than leaving it to a reader to notice.
#
# ⛔ DO NOT SWEEP THESE TO MAKE A CHECKER GREEN. `cs.allow-jit` is very probably
# REQUIRED by the bundled CPython; removing it trades a notarization
# prerequisite for an app that does not launch. `get-task-allow` is the only key
# being deliberately turned off, and it is the one the notary rejects.
ENTITLEMENTS: dict[str, bool] = {
    "com.apple.security.app-sandbox": False,
    "com.apple.security.cs.allow-jit": True,
    "com.apple.security.network.client": True,
    "com.apple.security.network.server": True,
    "com.apple.security.files.user-selected.read-write": True,
    "com.apple.security.get-task-allow": False,
}

MACHO_MAGICS = {
    b"\xcf\xfa\xed\xfe",  # MH_MAGIC_64  (little-endian)
    b"\xce\xfa\xed\xfe",  # MH_MAGIC     (little-endian)
    b"\xca\xfe\xba\xbe",  # FAT_MAGIC
    b"\xbe\xba\xfe\xca",  # FAT_CIGAM
}


def is_macho(path: Path) -> bool:
    """Does this file begin with a Mach-O or fat-binary magic?

    Read by MAGIC rather than by extension: the slices that matter here are
    `.dylib`, `.so`, bare executables inside `Contents/MacOS`, and frameworks
    with no extension at all. An extension allow-list would miss most of them.
    """
    try:
        with open(path, "rb") as fh:
            return fh.read(4) in MACHO_MAGICS
    except OSError:
        return False


def has_real_identity(path: Path) -> bool:
    """Does this slice already carry a CMS signature naming a real identity?

    ⭐ THIS IS THE GUARD THAT KEEPS US OFF THIRD-PARTY CODE. `codesign -dvvv`
    prints an `Authority=` line only for a genuine signature; an ad-hoc one has
    no authority chain at all. So an `Authority=` hit means somebody with an
    actual certificate signed this, and re-signing it would replace their
    identity with our ad-hoc nothing.

    ⚠️ FAIL SAFE, NOT FAIL OPEN: if the probe itself errors we return True
    ("treat as third-party, leave alone"). Skipping a slice we could have
    hardened is a measurable shortfall the instrument will report; destroying a
    real signature is not recoverable from the build output.
    """
    try:
        out = subprocess.run(
            ["codesign", "-dvvv", str(path)],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return True
    blob = (out.stderr or "") + (out.stdout or "")
    return "Authority=" in blob


def find_slices(app: Path) -> list[Path]:
    """Every Mach-O file in the bundle, deepest first.

    ⚠️ DEEPEST FIRST IS LOAD-BEARING, not tidiness. codesign seals a bundle over
    its contents, so signing an outer bundle before its nested code invalidates
    the outer seal the moment the inner one changes. Nested code must be signed
    before the thing that contains it.
    """
    out = [p for p in app.rglob("*") if p.is_file() and not p.is_symlink() and is_macho(p)]
    out.sort(key=lambda p: len(p.parts), reverse=True)
    return out


def check_pyproject(root: Path) -> int:
    """Assert pyproject's declared entitlements match what this script applies.

    The two live apart on purpose (see ENTITLEMENTS above), and a silent drift
    between them is exactly the defect that would let a future editor change one
    and ship the other.
    """
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - py<3.11
        print("SKIP: tomllib unavailable", file=sys.stderr)
        return 0

    pyproject = root / "pyproject.toml"
    with open(pyproject, "rb") as fh:
        data = tomllib.load(fh)
    declared = data.get("tool", {}).get("flet", {}).get("macos", {}).get("entitlement")
    if declared is None:
        print(f"FAIL: [tool.flet.macos.entitlement] missing from {pyproject}", file=sys.stderr)
        return 1
    if declared != ENTITLEMENTS:
        print("FAIL: pyproject entitlements disagree with this script.", file=sys.stderr)
        for key in sorted(set(declared) | set(ENTITLEMENTS)):
            lhs, rhs = declared.get(key, "<absent>"), ENTITLEMENTS.get(key, "<absent>")
            if lhs != rhs:
                print(f"  {key}: pyproject={lhs!r} script={rhs!r}", file=sys.stderr)
        return 1
    print(f"OK: pyproject and script agree on {len(ENTITLEMENTS)} entitlements.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--app", help="path to the built .app bundle")
    ap.add_argument("--dry-run", action="store_true", help="list what would be signed, sign nothing")
    ap.add_argument(
        "--check-pyproject",
        action="store_true",
        help="assert pyproject's entitlements match this script's, then exit (runs anywhere)",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent

    if args.check_pyproject:
        return check_pyproject(root)

    if not args.app:
        print("FAIL: --app is required (or use --check-pyproject)", file=sys.stderr)
        return 2

    app = Path(args.app)
    if not app.is_dir() or app.suffix != ".app":
        print(f"CANNOT RUN: not an .app bundle: {app}", file=sys.stderr)
        return 2
    if sys.platform != "darwin":
        print(f"CANNOT RUN: this needs macOS, not {sys.platform}.", file=sys.stderr)
        print("⚠️  This is NOT a pass — the question was not asked.", file=sys.stderr)
        return 2
    if shutil.which("codesign") is None:
        print("CANNOT RUN: `codesign` not on PATH.", file=sys.stderr)
        return 2

    ents_path = Path(os.environ.get("TMPDIR", "/tmp")) / "ps386_entitlements.plist"
    with open(ents_path, "wb") as fh:
        plistlib.dump(ENTITLEMENTS, fh)
    print(f"entitlements written to {ents_path}")
    for key, value in ENTITLEMENTS.items():
        print(f"    {key} = {value}")

    slices = find_slices(app)
    print(f"\n{len(slices)} Mach-O slice(s) found in {app}")

    ours: list[Path] = []
    theirs: list[Path] = []
    for path in slices:
        (theirs if has_real_identity(path) else ours).append(path)

    print(f"  {len(ours)} ad-hoc/unsigned  -> WILL be re-signed (ours)")
    print(f"  {len(theirs)} carrying a real identity -> LEFT ALONE (third-party)")
    for path in theirs:
        print(f"      skip: {path.relative_to(app)}")

    if args.dry_run:
        print("\n--dry-run: nothing was signed.")
        return 0

    failures: list[tuple[Path, str]] = []
    for path in ours:
        cmd = [
            "codesign", "--force", "--sign", "-",
            "--options", "runtime",
            "--entitlements", str(ents_path),
            "--timestamp=none",
            str(path),
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            failures.append((path, (res.stderr or "").strip()))

    # The bundle itself last — it seals over everything signed above.
    cmd = [
        "codesign", "--force", "--sign", "-",
        "--options", "runtime",
        "--entitlements", str(ents_path),
        "--timestamp=none",
        str(app),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        failures.append((app, (res.stderr or "").strip()))

    print(f"\nre-signed {len(ours)} slice(s) + the bundle")

    if failures:
        print(f"\nFAILED on {len(failures)} item(s):", file=sys.stderr)
        for path, err in failures:
            print(f"  {path}: {err}", file=sys.stderr)
        return 1

    verify = subprocess.run(
        ["codesign", "--verify", "--deep", "--strict", "--verbose=2", str(app)],
        capture_output=True,
        text=True,
    )
    print("\n--- codesign --verify --deep --strict ---")
    print((verify.stderr or verify.stdout or "").strip())
    if verify.returncode != 0:
        print("FAIL: the bundle does not verify after re-signing.", file=sys.stderr)
        return 1

    print("\nOK: every targeted slice re-signed with --options runtime.")
    print(
        "\n⚠️  THIS IS NOT A NOTARIZED OR IDENTITY-SIGNED BUILD, and must not be\n"
        "    reported as one. The signature is still AD-HOC and carries no\n"
        "    certificate. What changed is that the two purchase-independent\n"
        "    rejection conditions are gone: the hardened runtime is on, and\n"
        "    get-task-allow is false. Notarization still needs the Apple\n"
        "    Developer Program membership, which is the owner's decision.\n"
        "\n⛔  A PASS HERE IS NOT OUTCOME 4. It says the bytes changed; it does\n"
        "    NOT say the app still launches or still spawns an engine. Launch it."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
